# Generated by Django 3.0.4 on 2020-03-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0003_region_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
    ]
