# Generated by Django 3.0.4 on 2020-03-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0005_region_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcases',
            name='reg_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region'),
        ),
    ]
