# Generated by Django 3.0.4 on 2020-03-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0006_newcases_reg_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcases',
            name='region',
        ),
    ]
