# Generated by Django 3.0.4 on 2020-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0007_remove_newcases_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='station',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='tmax',
        ),
        migrations.AddField(
            model_name='temperature',
            name='temp',
            field=models.FloatField(default=0, verbose_name='Temperature'),
            preserve_default=False,
        ),
    ]
