# Generated by Django 3.0.4 on 2020-04-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0009_temperature_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country_alt',
            field=models.CharField(max_length=100, null=True, verbose_name='Alternative Country Name'),
        ),
    ]
