# Generated by Django 3.0.4 on 2020-04-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0011_region_name_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Count')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Count')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region')),
            ],
        ),
    ]
