# Generated by Django 3.0.4 on 2020-04-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0012_cases_deaths'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCases',
        ),
    ]
