# Generated by Django 3.0.4 on 2020-04-04 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0015_cases_deaths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('temp', models.FloatField(verbose_name='Temperature')),
                ('dewpoint', models.FloatField(verbose_name='Dewpoint Temperature')),
                ('uvb', models.FloatField(verbose_name='UV Radiation')),
                ('evap', models.FloatField(verbose_name='Evaporation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region')),
            ],
        ),
    ]
