# Generated by Django 3.0.4 on 2020-04-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0016_measurements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
