# Generated by Django 3.0.4 on 2020-04-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0017_delete_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='A00_04B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 0 to 4'),
        ),
        migrations.AddField(
            model_name='region',
            name='A05_09B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 5 to 9'),
        ),
        migrations.AddField(
            model_name='region',
            name='A10_14B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 10 to 14'),
        ),
        migrations.AddField(
            model_name='region',
            name='A15_19B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 15 to 19'),
        ),
        migrations.AddField(
            model_name='region',
            name='A20_24B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 20 to 24'),
        ),
        migrations.AddField(
            model_name='region',
            name='A25_29B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 25 to 29'),
        ),
        migrations.AddField(
            model_name='region',
            name='A30_34B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 30 to 34'),
        ),
        migrations.AddField(
            model_name='region',
            name='A35_39B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 35 to 39'),
        ),
        migrations.AddField(
            model_name='region',
            name='A40_44B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 40 to 44'),
        ),
        migrations.AddField(
            model_name='region',
            name='A45_49B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 45 to 49'),
        ),
        migrations.AddField(
            model_name='region',
            name='A50_54B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 50 to 54'),
        ),
        migrations.AddField(
            model_name='region',
            name='A55_59B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 55 to 59'),
        ),
        migrations.AddField(
            model_name='region',
            name='A60_64B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 60 to 64'),
        ),
        migrations.AddField(
            model_name='region',
            name='A65PLUSB',
            field=models.PositiveIntegerField(null=True, verbose_name='Aulation 65 and Older'),
        ),
    ]
