# Generated by Django 3.0.4 on 2020-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0019_auto_20200406_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='A04UNDERB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 4 and Under'),
        ),
        migrations.AddField(
            model_name='region',
            name='A05_19B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 5 to 19'),
        ),
        migrations.AddField(
            model_name='region',
            name='A05_24B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 5 to 24'),
        ),
        migrations.AddField(
            model_name='region',
            name='A05_29B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 5 to 29'),
        ),
        migrations.AddField(
            model_name='region',
            name='A05_34B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 5 to 34'),
        ),
        migrations.AddField(
            model_name='region',
            name='A09UNDERB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 9 and Under'),
        ),
        migrations.AddField(
            model_name='region',
            name='A14UNDERB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 14 and Under'),
        ),
        migrations.AddField(
            model_name='region',
            name='A15_24B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 15 to 24'),
        ),
        migrations.AddField(
            model_name='region',
            name='A15_29B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 15 to 29'),
        ),
        migrations.AddField(
            model_name='region',
            name='A15_34B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 15 to 34'),
        ),
        migrations.AddField(
            model_name='region',
            name='A19UNDERB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 19 and Under'),
        ),
        migrations.AddField(
            model_name='region',
            name='A20_29B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 20 to 29'),
        ),
        migrations.AddField(
            model_name='region',
            name='A20_34B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 20 to 34'),
        ),
        migrations.AddField(
            model_name='region',
            name='A24UNDERB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 24 and Under'),
        ),
        migrations.AddField(
            model_name='region',
            name='A29UNDERB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 29 and Under'),
        ),
        migrations.AddField(
            model_name='region',
            name='A34UNDERB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 34 and Under'),
        ),
        migrations.AddField(
            model_name='region',
            name='A35_54B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 35 to 54'),
        ),
        migrations.AddField(
            model_name='region',
            name='A35_64B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 35 to 64'),
        ),
        migrations.AddField(
            model_name='region',
            name='A40_54B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 40 to 54'),
        ),
        migrations.AddField(
            model_name='region',
            name='A40_64B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 40 to 64'),
        ),
        migrations.AddField(
            model_name='region',
            name='A45_54B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 45 to 54'),
        ),
        migrations.AddField(
            model_name='region',
            name='A45_64B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 45 to 64'),
        ),
        migrations.AlterField(
            model_name='region',
            name='A65PLUSB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 65 and Older'),
        ),
        migrations.AlterField(
            model_name='region',
            name='A70PLUSB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 70 and Older'),
        ),
        migrations.AlterField(
            model_name='region',
            name='A75PLUSB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 75 and Older'),
        ),
        migrations.AlterField(
            model_name='region',
            name='A80PLUSB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 80 and Older'),
        ),
        migrations.AlterField(
            model_name='region',
            name='A85PLUSB',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 85 and Older'),
        ),
    ]
