# Generated by Django 3.0.4 on 2020-04-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0021_auto_20200406_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='A05_14B',
            field=models.PositiveIntegerField(null=True, verbose_name='Population 5 to 14'),
        ),
    ]
