# Generated by Django 3.0.4 on 2020-04-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0022_region_a05_14b'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='density',
            field=models.FloatField(null=True, verbose_name='Density'),
        ),
    ]
