# Generated by Django 3.0.4 on 2020-04-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0023_region_density'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='density',
        ),
    ]
