# Generated by Django 3.0.4 on 2020-04-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0024_remove_region_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='LAND_A_KM',
            field=models.FloatField(null=True, verbose_name='Land Area'),
        ),
        migrations.AddField(
            model_name='region',
            name='land_density',
            field=models.FloatField(null=True, verbose_name='Land Density'),
        ),
    ]
