# Generated by Django 3.0.4 on 2020-04-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0025_auto_20200407_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='dewpoint',
            field=models.FloatField(null=True, verbose_name='Dewpoint Temperature'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='evap',
            field=models.FloatField(null=True, verbose_name='Evaporation'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='temp',
            field=models.FloatField(null=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='uvb',
            field=models.FloatField(null=True, verbose_name='UV Radiation'),
        ),
    ]
