# Generated by Django 3.0.4 on 2020-04-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0026_auto_20200407_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='city_dens',
            field=models.FloatField(null=True, verbose_name='Density of Largest City'),
        ),
    ]
