# Generated by Django 3.0.4 on 2020-04-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0027_region_city_dens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('alpha2', models.CharField(max_length=2, verbose_name='Alpha-2 Code')),
                ('alpha3', models.CharField(max_length=3, verbose_name='Alpha-3 Code')),
                ('numbeic', models.PositiveSmallIntegerField(verbose_name='Numeric')),
            ],
        ),
    ]
