# Generated by Django 3.0.4 on 2020-04-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0029_remove_country_numbeic'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='numeric',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Numeric Code'),
            preserve_default=False,
        ),
    ]
