# Generated by Django 3.0.4 on 2020-04-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0032_auto_20200410_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region')),
            ],
        ),
    ]
