# Generated by Django 3.0.4 on 2020-04-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0033_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pollutants',
        ),
    ]
