# Generated by Django 3.0.4 on 2020-04-10 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0034_delete_pollutants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('pollutant', models.CharField(max_length=20, verbose_name='Pollutant')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Count')),
                ('minimum', models.FloatField(verbose_name='Minimum')),
                ('maximum', models.FloatField(verbose_name='Maximum')),
                ('median', models.FloatField(verbose_name='Median')),
                ('variance', models.FloatField(verbose_name='Variance')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Country')),
            ],
        ),
    ]
