# Generated by Django 3.0.4 on 2020-04-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0036_remove_pollutant_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollutant',
            unique_together={('date', 'city', 'pollutant')},
        ),
        migrations.CreateModel(
            name='Strindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('s1', models.PositiveSmallIntegerField(verbose_name='School Closing')),
                ('s2', models.PositiveSmallIntegerField(verbose_name='Workplace Closing')),
                ('s3', models.PositiveSmallIntegerField(verbose_name='Cancel Public Events')),
                ('s4', models.PositiveSmallIntegerField(verbose_name='Close Public Transport')),
                ('s5', models.PositiveSmallIntegerField(verbose_name='Public Information Campaigns')),
                ('s6', models.PositiveSmallIntegerField(verbose_name='Restrictions on Internal Movement')),
                ('s7', models.PositiveSmallIntegerField(verbose_name='International Travel Controls')),
                ('s8', models.PositiveSmallIntegerField(verbose_name='Fiscal Measures')),
                ('s9', models.PositiveSmallIntegerField(verbose_name='Monetary Measures')),
                ('s10', models.PositiveSmallIntegerField(verbose_name='Emergency Investment in Health Care')),
                ('s11', models.PositiveSmallIntegerField(verbose_name='Investment in Vaccines')),
                ('s12', models.PositiveSmallIntegerField(verbose_name='Testing Framework')),
                ('s13', models.PositiveSmallIntegerField(verbose_name='Contact Tracing')),
                ('strindex', models.FloatField(verbose_name='Stringency Index')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Country')),
            ],
            options={
                'unique_together': {('date', 'country')},
            },
        ),
    ]
