# Generated by Django 3.0.4 on 2020-04-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0037_auto_20200424_1610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strindex',
            unique_together=set(),
        ),
    ]
