# Generated by Django 3.0.4 on 2020-04-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0038_auto_20200424_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strindex',
            name='s1',
            field=models.SmallIntegerField(verbose_name='School Closing'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s10',
            field=models.SmallIntegerField(verbose_name='Emergency Investment in Health Care'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s11',
            field=models.SmallIntegerField(verbose_name='Investment in Vaccines'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s12',
            field=models.SmallIntegerField(verbose_name='Testing Framework'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s13',
            field=models.SmallIntegerField(verbose_name='Contact Tracing'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s2',
            field=models.SmallIntegerField(verbose_name='Workplace Closing'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s3',
            field=models.SmallIntegerField(verbose_name='Cancel Public Events'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s4',
            field=models.SmallIntegerField(verbose_name='Close Public Transport'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s5',
            field=models.SmallIntegerField(verbose_name='Public Information Campaigns'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s6',
            field=models.SmallIntegerField(verbose_name='Restrictions on Internal Movement'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s7',
            field=models.SmallIntegerField(verbose_name='International Travel Controls'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s8',
            field=models.SmallIntegerField(verbose_name='Fiscal Measures'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='s9',
            field=models.SmallIntegerField(verbose_name='Monetary Measures'),
        ),
        migrations.AlterUniqueTogether(
            name='strindex',
            unique_together={('date', 'country')},
        ),
    ]
