# Generated by Django 3.0.4 on 2020-04-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0039_auto_20200424_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('retail_n_rec', models.FloatField(verbose_name='Retail & Recreation')),
                ('groc_n_pharm', models.FloatField(verbose_name='Grocery & Pharmacy')),
                ('parks', models.FloatField(verbose_name='Parks')),
                ('transit', models.FloatField(verbose_name='Transit')),
                ('workplaces', models.FloatField(verbose_name='Work Places')),
                ('residential', models.FloatField(verbose_name='Residential')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region')),
            ],
            options={
                'unique_together': {('date', 'region')},
            },
        ),
    ]
