# Generated by Django 3.0.4 on 2020-04-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0040_mobility'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobility',
            unique_together=set(),
        ),
    ]
