# Generated by Django 3.0.4 on 2020-04-25 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0041_auto_20200424_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('neoplasms', models.PositiveSmallIntegerField(verbose_name='NeoPlasms')),
                ('blood', models.PositiveSmallIntegerField(verbose_name='Blood-based')),
                ('endo', models.PositiveSmallIntegerField(verbose_name='Endocrine')),
                ('mental', models.PositiveSmallIntegerField(verbose_name='Mental')),
                ('nervous', models.PositiveSmallIntegerField(verbose_name='Nervous System')),
                ('circul', models.PositiveSmallIntegerField(verbose_name='Circulatory')),
                ('infectious', models.PositiveSmallIntegerField(verbose_name='Infectious')),
                ('respir', models.PositiveSmallIntegerField(verbose_name='Respiratory')),
                ('digest', models.PositiveSmallIntegerField(verbose_name='Digestive')),
                ('skin', models.PositiveSmallIntegerField(verbose_name='Skin-related')),
                ('musculo', models.PositiveSmallIntegerField(verbose_name='Musculo-skeletal')),
                ('genito', models.PositiveSmallIntegerField(verbose_name='Genitourinary')),
                ('childbirth', models.PositiveSmallIntegerField(verbose_name='Maternal and Childbirth')),
                ('perinatal', models.PositiveSmallIntegerField(verbose_name='Perinatal')),
                ('congenital', models.PositiveSmallIntegerField(verbose_name='Congenital')),
                ('other', models.PositiveSmallIntegerField(verbose_name='Other')),
                ('external', models.PositiveSmallIntegerField(verbose_name='External')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region')),
            ],
        ),
    ]
