# Generated by Django 3.0.4 on 2020-04-25 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0042_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='casestudy.Country'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region'),
        ),
    ]
