# Generated by Django 3.0.4 on 2020-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0043_auto_20200425_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='blood',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Blood-based'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='childbirth',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Maternal and Childbirth'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='circul',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Circulatory'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='congenital',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Congenital'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='digest',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Digestive'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='endo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Endocrine'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='external',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='External'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='genito',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Genitourinary'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='infectious',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Infectious'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='mental',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Mental'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='musculo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Musculo-skeletal'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='neoplasms',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='NeoPlasms'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='nervous',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Nervous System'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='other',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='perinatal',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Perinatal'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='respir',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Respiratory'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='skin',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Skin-related'),
        ),
    ]
