# Generated by Django 3.0.4 on 2020-04-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0047_auto_20200426_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('gdp', models.FloatField(verbose_name='GDP PPP, 2016, Current Dollars')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region')),
            ],
        ),
    ]
