# Generated by Django 3.0.4 on 2020-04-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0048_gdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdp',
            name='gdp',
            field=models.FloatField(null=True, verbose_name='GDP PPP, 2016, Current Dollars'),
        ),
    ]
