# Generated by Django 3.0.4 on 2020-05-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0050_auto_20200428_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleMobility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('driving', models.FloatField(verbose_name='Driving')),
                ('walking', models.FloatField(verbose_name='Walking')),
                ('transit', models.FloatField(verbose_name='Transit')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region')),
            ],
            options={
                'unique_together': {('date', 'region')},
            },
        ),
    ]
