# Generated by Django 3.0.4 on 2020-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0051_applemobility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applemobility',
            name='driving',
            field=models.FloatField(null=True, verbose_name='Driving'),
        ),
        migrations.AlterField(
            model_name='applemobility',
            name='transit',
            field=models.FloatField(null=True, verbose_name='Transit'),
        ),
        migrations.AlterField(
            model_name='applemobility',
            name='walking',
            field=models.FloatField(null=True, verbose_name='Walking'),
        ),
    ]
