# Generated by Django 3.0.4 on 2020-05-18 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0052_auto_20200515_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cases',
            unique_together={('date', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='deaths',
            unique_together={('date', 'region')},
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('tests', models.PositiveSmallIntegerField(verbose_name='Count')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casestudy.Region')),
            ],
            options={
                'unique_together': {('date', 'region')},
            },
        ),
    ]
