# Generated by Django 3.0.4 on 2020-05-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0053_auto_20200518_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='cases',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='tests',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Count'),
        ),
    ]
