# Generated by Django 3.0.4 on 2020-05-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0054_auto_20200530_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_test',
            field=models.IntegerField(null=True, verbose_name='Count'),
        ),
    ]
