# Generated by Django 3.0.4 on 2020-05-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0055_tests_test_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='tests',
        ),
    ]
