# Generated by Django 3.0.4 on 2020-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0057_auto_20200530_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='float_test',
        ),
        migrations.AddField(
            model_name='tests',
            name='tests',
            field=models.FloatField(null=True, verbose_name='Count'),
        ),
    ]
