# Generated by Django 3.0.4 on 2020-05-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0058_auto_20200530_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='Region Code'),
        ),
    ]
