# Generated by Django 3.0.4 on 2020-06-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0059_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='cases',
            field=models.IntegerField(null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='deaths',
            name='deaths',
            field=models.IntegerField(verbose_name='Count'),
        ),
    ]
