# Generated by Django 3.0.4 on 2020-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0060_auto_20200612_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='blood',
            field=models.IntegerField(null=True, verbose_name='Blood-based'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='childbirth',
            field=models.IntegerField(null=True, verbose_name='Maternal and Childbirth'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='circul',
            field=models.IntegerField(null=True, verbose_name='Circulatory'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='congenital',
            field=models.IntegerField(null=True, verbose_name='Congenital'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='digest',
            field=models.IntegerField(null=True, verbose_name='Digestive'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='endo',
            field=models.IntegerField(null=True, verbose_name='Endocrine'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='external',
            field=models.IntegerField(null=True, verbose_name='External'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='genito',
            field=models.IntegerField(null=True, verbose_name='Genitourinary'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='infectious',
            field=models.IntegerField(null=True, verbose_name='Infectious'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='mental',
            field=models.IntegerField(null=True, verbose_name='Mental'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='musculo',
            field=models.IntegerField(null=True, verbose_name='Musculo-skeletal'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='neoplasms',
            field=models.IntegerField(null=True, verbose_name='NeoPlasms'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='nervous',
            field=models.IntegerField(null=True, verbose_name='Nervous System'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='other',
            field=models.IntegerField(null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='perinatal',
            field=models.IntegerField(null=True, verbose_name='Perinatal'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='respir',
            field=models.IntegerField(null=True, verbose_name='Respiratory'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='skin',
            field=models.IntegerField(null=True, verbose_name='Skin-related'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='gdp',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='c1',
            field=models.IntegerField(null=True, verbose_name='School Closing'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='c2',
            field=models.IntegerField(null=True, verbose_name='Workplace Closing'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='c3',
            field=models.IntegerField(null=True, verbose_name='Cancel Public Events'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='c4',
            field=models.IntegerField(null=True, verbose_name='Restrictions on Gatherings'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='c5',
            field=models.IntegerField(null=True, verbose_name='Close Public Transport'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='c6',
            field=models.IntegerField(null=True, verbose_name='Stay-at-Home Requirements'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='c7',
            field=models.IntegerField(null=True, verbose_name='Restrictions on Internal Movement'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='c8',
            field=models.IntegerField(null=True, verbose_name='International Travel Controls'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='e1',
            field=models.IntegerField(null=True, verbose_name='Income Support'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='e2',
            field=models.IntegerField(null=True, verbose_name='Debt / Contract Relief'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='e3',
            field=models.IntegerField(null=True, verbose_name='Fiscal Measures'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='e4',
            field=models.IntegerField(null=True, verbose_name='International Support'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='h1',
            field=models.IntegerField(null=True, verbose_name='Public Information Campaigns'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='h2',
            field=models.IntegerField(null=True, verbose_name='Testing Policy'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='h3',
            field=models.IntegerField(null=True, verbose_name='Contact Tracing'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='h4',
            field=models.IntegerField(null=True, verbose_name='Emergency Investment in Health Care'),
        ),
        migrations.AlterField(
            model_name='strindex',
            name='h5',
            field=models.IntegerField(null=True, verbose_name='Investment in Vaccines'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
