# Generated by Django 3.0.4 on 2020-08-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0062_hospitalizations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobility',
            unique_together={('date', 'region')},
        ),
    ]
